### ISSUE TITLE
How to show the ContentDetent before AnchorDetent?

### ISSUE THREAD

**Issue by dg2k** [the49code/The49.Maui.BottomSheet#21]
Hello,

One usage I found effective for Maui.BottomSheet is to display **Usage Tips** whereby e-learning type Help needs to be integrated with an App. There are situations where I want to show the Content rather than the minimalist AnchorDetent (my anchor being near the very top) and would like to have both ContentDetent and AnchorDetent.

Unless I missed the obvious, I see no option for showing a specific Detent first. I know the default is great, but such added options will only expand the usage scope for this great package, particularly for educational apps.

How do you set ContentDetent as a default on invoking the Show() method?

It would be great if the default behavior can be overridden like  `bottomSheet.Show(startWith:DetentType.Content)`.

**Comment by paulvarache** [comment]
I think this makes sense. Currently the detents are sorted by height after being calculated so that the smallest one opens by default.

I will probably add a `CurrentDetent` or `SelectedDetent` two way property to be able to react to changes and programmatically go to a detent.

Adding it as an option for the `Show` method also makes sense.

This is all kind of blocked behind iOS' implementation as custom detents do not have access to the options we'd need to implement this. There is a workaround I am looking into that would unblock this and other features so that Android doesn't get a worse feature set because of iOS' limitations.

I will leave this issue open as a tracker for the feature

**Comment by paulvarache** [comment]
Hi,

rc1 was just released with a few changes that should cover this issue:

`SelectedDetent` was added. This is a two way bindable property to control the current detent programmatically. Setting this value before showing the sheet will open to that detent first.

Additionally, `IsDefault` can be set to true on a Detent in xaml will automatically select that detent when showing
